analyzer:
  exclude:
    - lib/bases/*.dart
    - lib/i18n/*.dart
    - lib/pop/*.dart
    - lib/refresh/*.dart
    - lib/utils/*.dart
    - lib/widget/*.dart
    - lib/core.dart
  errors:
    undefined_prefixed_name: ignore
